version: '3.8'

networks:
  pku-network:
services:
  api:
    container_name: pku-backend
    image: pku-backend-dev:1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - pku-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:debug
    restart: unless-stopped
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - mongodb-data:/data/db
    networks:
      - pku-network
    ports:
      - 27017:27017
    env_file:
      - .env
    restart: unless-stopped
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    volumes:
      - mongodb-data:/data/db
    depends_on:
      - mongodb
    networks:
      - pku-network
    ports:
      - 8081:8081
    env_file:
      - .env
    restart: unless-stopped
volumes:
  mongodb-data:
    name: mongodb-data